### ISSUE TITLE
Build error on Xcode 12.5, macOS 11.3

### ISSUE THREAD

**Issue by alalamav** [apache/cordova-osx#112] opened 2021-07-20 15:24 UTC
# Bug Report

### What is expected to happen?
A cordova-osx project builds successfully on Xcode 12.5.

### What does actually happen?
Since updating to macOS BigSur (11.3.1) and Xcode 12.5.1 cordova-osx fails to build with:

```
platforms/osx/CordovaLib/CordovaLib/Classes/CDVBridge.m:77:22: error: too many arguments to function call, expected 0, have
objc_msgSend(obj, normalSelector, command);
~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'ObjectiveC' imported from /Users/fortuna/firehook/outline-client/platforms/osx/CordovaLib/CordovaLib/Classes/CDVBridge.m:22
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/objc/message.h:63:1: note: 'objc_msgSend' declared here
objc_msgSend(void /* id self, SEL op, ... */ )
^
```

This error occurs in CDVCommandQueue.m and CDVBridge.m. 

A solution could be to define a more specific selector that conforms to the new SDK.

### Command or Code
`cordova compile`

### Environment, Platform, Device
macOS BigSur 11.3.1
Xcode 12.5.1
SDK MacOSX11.3

### Version information
cordova-cli 10.0.0
cordova-osx 6.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by fortuna** [comment] 2021-07-21 18:17
FYI, I was able to build from Xcode, though not from the command-line. I still don't know why.

**Comment by fortuna** [comment] 2021-09-16 20:17
Here is the in-depth explanation of what the issue is: https://www.mikeash.com/pyblog/objc_msgsends-new-prototype.html.

Fortunately the fix is easy. Can the repo owners please merge the fix?

**Comment by fortuna** [comment] 2022-02-05 18:58
This can be closed as it was fixed by https://github.com/apache/cordova-osx/pull/105.

**Closed** 2022-02-06 01:40 UTC
